### ISSUE TITLE
Firebase user control

### ISSUE THREAD

**Issue by fxo140130** [firebase/functions-samples#111]
Is there any way to deny some part of an App to a specific user using Firebase?

The flow is as follow : 

- User X is authenticated and fill some field in the app and have his/her state on pending. 

- Firebase admin  receive the data input from the end user, validate it and release the account so He/she can have access to the remaining part of the App. 

I have been working on this the whole day.  Hope someone help.

**Comment by prescottprue** [comment]
There are multiple parts to what you are asking about, but I believe most of it can be accomplished without using cloud functions at all

### Page/Route Access
This will take writing app logic, which is not necessarily related to this repository (it is for samples of cloud functions).

As a thought: You could have a parameter `approved: true` on the users account be required in your routing logic, but again hard to say since this is within your application.

### Securing Data
Comes down to Firebase rules that would be based on whether or not the user has a matching parameter (such as `approve: true`). This not really related to this repo unless you are talking about creating custom token, which is done in the [username-password-auth example](https://github.com/firebase/functions-samples/tree/master/username-password-auth)

### "Receive data input from user"
You might not need a Cloud Function to do this either if another user of the application is the admin.

If you need to send an email there [are examples](https://github.com/firebase/functions-samples/tree/master/email-confirmation) that include emailing users, you could change that to email your "admin" email account when users signup. Then it would be up to the email receiver to add `approved: true` to the user mentioned in the email.

**Comment by fxo140130** [comment]
@prescottprue 

That all I need. Thanks Sir.
