### ISSUE TITLE
[sample request ] paypal sample

### ISSUE THREAD

**Issue by gujiman** [firebase/functions-samples#114]
Have a request for a new sample?
================================
Is it possible to add a paypal sample into functions? 

Example:
1. A user buys a service or product via paypal.
2. Paypal triggers it's webhook to Functions.
3. Functions updates the firebase database and send a push notification to the user.

**Comment by berchik** [comment]
Its possible. Basically add paypal-rest-sdk to the functions directory. 

In the index.js execute paypal.configure with the client id + secret you’ve created to the app in your paypal developer console.

Next, depends on your needs (payment/subscription etc), create the objects you need (based on the paypal rest docs) and execute the functions. For example, for one-time payment use the following functions:
paypal.payment.create
paypal.payment.execute

remember that ‘create’ takes a PAYMENT OBJECT as first param, and there you can set ‘return_url’ that will point to the second function ‘execute’, and so you call the ‘create’ which - when finished with user approval on paypal - will call the ‘execute’.

Hope this gives you few starting points. It is very confusing in the beginning, mainly due to the psychedelic docs and examples at paypal, with some wrong instructions and some black holes, and several bugs in the developer console and few sandbox horrors, but once you get used to it its not that difficult. Make sure you log all return values and post results, it will vlarify what is really going on.

Good luck!

**Comment by nicolasgarnier** [comment]
We now have a Paypal sample: https://github.com/firebase/functions-samples/tree/master/paypal

**Comment by devhopes-ca** [comment]
Hi, I have implemented PayPal payouts through my Android app but unable to get implemented in my IOS app.  Basically, when the GET PAYOUTS button is selected, a POST request is sent to the firebase-function and then the data is sent to PayPal.  When I see the firebase-logs, I see the data is captured through a console.log() but isn't retained through PayPal and cannot figure out why.  Please see my index.js file attached and my iOS swift payoutRequest() method
[index_js.txt](https://github.com/firebase/functions-samples/files/2716509/index_js.txt)

[payoutRequest.txt](https://github.com/firebase/functions-samples/files/2716511/payoutRequest.txt)

Any help would be greatly appreciated as I have been working on this for a month with no resolution in sight.  
. No one on stack overflow has been able to answer my posts on this.
