### ISSUE TITLE
Issue with firebase-auth sample 

### ISSUE THREAD

**Issue by tejasrsuthar** [firebase/functions-samples#190]
I'm using firebase-auth example and found one error in firebase console log.

### Error Description 
Error: getaddrinfo ENOTFOUND www.linkedin.com www.linkedin.com:443
    at errnoException (dns.js:28:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:76:26)

### Steps to reproduce the issue
Login with Linked in from this sample app: https://linkedin-auth-example.firebaseapp.com

After successful authentication, you will get Please wait message and firebase is responding with code ans state but will not go beyond further and provide token

Here is the snap for firebase console log. 
https://www.dropbox.com/s/w5v14xuehpjyb6z/Screenshot%202017-07-12%2012.04.55.png?dl=0

**Comment by nicolasgarnier** [comment]
Hey @tejasrsuthar,

It seems that the issue is that you did not enable billing on your project.
This sample needs you to have billing enabled because projects without billing are only allowed to do requests to Google Services and so since the app needs to do requests to LinkedIn you'll have to enable billing.

**Comment by tejasrsuthar** [comment]
Oh ok. I'll enable billing and check again. 

Thanks for your update. :+1:

**Comment by minhdongsss** [comment]
@tejasrsuthar It worked?

**Comment by tejasrsuthar** [comment]
@minhdongsss sorry, I didn't get time to check this.

**Comment by minhdongsss** [comment]
@tejasrsuthar hihi
