### ISSUE TITLE
generate-thumbnail: `Error serializing return value: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by deremer** [firebase/functions-samples#193]
In this sample: https://github.com/firebase/functions-samples/tree/master/generate-thumbnail

We routinely see the error `Error serializing return value: TypeError: Converting circular structure to JSON` in the logs during function execution.

We've been trying to isolate exactly the point of failure, but testing and debugging with cloud functions is a bit tricky. 

Logging it here in case someone at Firebase has an idea.

**Comment by Jasperav** [comment]
Anyone fixed it?

**Comment by nicolasgarnier** [comment]
This usually happens if you are returning an object that is not serializable to JSON, for instance if it has a circular structure.

This used to happen with `.push()` and `.transactions()` Firebase RTDB operations.

Can you try modifying [index.js - l.107 of the sample](https://github.com/firebase/functions-samples/blob/master/generate-thumbnail/functions/index.js#L107)

from:

```js
return admin.database().ref('images').push({path: fileUrl, thumbnail: thumbFileUrl});
```

to:

```js
return admin.database().ref('images').push({path: fileUrl, thumbnail: thumbFileUrl})
    .then(() => console.log('Thumbnail URLs saved.'));
```

Does this fixes the issue?
Are you guys getting this with the latest version of the Firebase NPM package? Please make sure you get the latest one. If you are on the latest one please let us know as this could be a regression.

**Comment by Jasperav** [comment]
How can this solve the circular error? I have another issue here: https://stackoverflow.com/questions/45150056/debugging-firebase-circular-reference does console logging solve the problem? Looks weird to me...

**Comment by nicolasgarnier** [comment]
This can solve the circular error because you would now be returning `console.log('Thumbnail URLs saved.')` which is like returning `undefined` instead of returning the Firebase Reference object returned by `admin.database().ref('images').push(...)` which is a complex object and might contain the circular dependency (it used to contain a circular dependency in the past).

**Comment by deremer** [comment]
We ended up refactoring to use typescript and await (since that's how the rest of our functions are written), and after the re-write we no longer have this issue.

Unfortunately, I didn't test adding another `then()` with a `console.log()`, so I can't confirm that it works.

**Comment by dannycochran** [comment]
still getting this issue even when returning a promise instead of the firebase.Promise resulting from transaction:

```javascript
export default functions.database.ref(listenToPath).onWrite(event => {
  if (event.data.changed()) {
    return new Promise((resolve, reject) => {
      ref.transaction(previousValue => previousValue + 1).then(resolve, reject).catch(reject);
    });
  }
});
```

**Comment by inlined** [comment]
That code is a noop from just returning `ref.transaction` (That it's a noop is actually part of the acceptance test for a Promise implementation).

The problem you're running into is that the promised value that `ref.transaction` returns isn't serializeable as JSON. The easiest way to fix this (before we fix it in the Firebase SDK) is to _transform_ the value to something like null.

```js
export default functions.database.ref(listenToPath).onWrite(event => {
  if (event.data.changed()) {
      return ref.transaction(previousValue => previousValue + 1).then(() => null);
  }
});
```

That `() => null` transforms any success of `TransactionResult` to a success of `typeof null`

**Comment by dannycochran** [comment]
@inlined thanks for the workaround!

**Comment by skwny** [comment]
This didn't work for my use case. I'm getting the serializing error when trying to do the following:

`exports.invite_decrement = functions.database.ref(inviteRef).onDelete(event => {
  return admin.database().ref('/organizations/' + event.params.orgId + '/count_invite').transaction((current) => {
    if (current >= 1) return (current - 1);
    else return;
  });
});`

If I remove the  `if(current >=1)`, I do not receive an error. 

I tried adding `.then(() => null);` after my transaction but it did not do the trick.
