### ISSUE TITLE
How does gcs work without projectId and keyFilename? For me it's not working.

### ISSUE THREAD

**Issue by ishandutta2007** [firebase/functions-samples#223]
https://github.com/firebase/functions-samples/blob/a122f190f579b2178d6a49e9757ec1e52f97362c/moderate-images/functions/index.js#L20

I am getting the follwoing error:

> 
> error:  { SigningError: Could not get credentials without a JSON, pem, or p12 keyfile.
>     at /user_code/node_modules/@google-cloud/storage/src/file.js:1479:16
>     at getAuthClient (/user_code/node_modules/@google-cloud/storage/node_modules/google-auto-auth/index.js:132:9)
>     at process._tickDomainCallback (internal/process/next_tick.js:135:7)
>   message: 'Could not get credentials without a JSON, pem, or p12 keyfile.' }

**Comment by inlined** [comment]
Is this on production or your local machine? When you initialize the SDK without parameters, it reads your machine's local state to figure out how to initialize.

**Comment by nicolasgarnier** [comment]
@ishandutta2007 the `require('@google-cloud/storage')()` call will configure the Google Cloud SDK automatically if it is ran in a Google Cloud environment (Google Cloud Functions, App Engine, Google Compute Engine Instance).

It looks like you tried to run the code locally and directly using Node. The Google Cloud Storage triggers would have to be ran in a Cloud Function emulator but we do not yet have one for Cloud Storage triggers. 

Try deploying the sample so that the Cloud Function run in the production environment. For this simply follow [the instructions on the README](https://github.com/firebase/functions-samples/blob/master/moderate-images/README.md).
