### ISSUE TITLE
functions-samples: child-count

### ISSUE THREAD

**Issue by kamvoick** [firebase/functions-samples#238]
I got a question which could be use case within that child-count sample. If I want to delete my post it will fire 32 x deletion trigger "countlikechange" and once "recountlikes" even if it's a ghost, am i right? If so, how to prevent this?

**Comment by nicolasgarnier** [comment]
You are right here. It's bad because the whole node will not get deleted, a `likes_count` of 0 will be re-written at the path.

I guess the only way is to check if some field of the post exists. For instance:

```js
// Keeps track of the length of the 'likes' child list in a separate property.
exports.countlikechange = functions.database.ref('/posts/{postid}/likes/{likeid}').onWrite(event => {
  const collectionRef = event.data.ref.parent;
  const countRef = collectionRef.parent.child('likes_count');

  //Let's see if the collection has a title. If not it must be because it has been deleted.
  return collectionRef.parent.child('title').once('value').then(snap => {
    if(snap.exists()) {
      // Return the promise from countRef.transaction() so our function 
      // waits for this async event to complete before it exits.
      return countRef.transaction(current => {
        if (event.data.exists() && !event.data.previous.exists()) {
          return (current || 0) + 1;
        }
        else if (!event.data.exists() && event.data.previous.exists()) {
          return (current || 0) - 1;
        }
      }).then(() => {
        console.log('Counter updated.');
      });
    }
  });
});
```

That will be an extra call every time there is a new Like though...

Alternatively you can simply block writes on the `like_count` node using security rules if the post does not exists. The cloud function will trigger 36 times but this will make the write calls fails so at least you won't have a dangling like_count in an empty post.
So you might have to check what happens the most frequently (post deletion) vs overall likes.

**Comment by augusto-nc** [comment]
Instead "onDelete trigger" you can use "onUpdate", when user wants to remove, he sets the value false, and who deletes is the function

**Comment by generic-github-user** [comment]
@nicolasgarnier Thank you so much! This is exactly what I was looking for. Works perfectly!
