### ISSUE TITLE
How to get image URL after use Sharp for image compression

### ISSUE THREAD

**Issue by lagmanzaza** [firebase/functions-samples#243]
I use cloud function for compressing the images. I don't know to get image URL after compressing

**Comment by joemanfoo** [comment]
```
// upload file
        .then(() => {
		      if (debug) {
		        console.log(`Uploading ${tmpFile} to ${FilePath}`)
		      }
		      return bucket.upload(tmpFile, { destination: FilePath })
		    })
        // make download URL
        .then(file => {
		      if (debug) {
		        console.log('Generating Long-term download url')
		      }

		      // save the file's metadata to our inventory item
		      item.image = file[0].metadata

		      let config = {
		        action: 'read',
		        expires: '12-31-2591'
		      }
		      return file[0].getSignedUrl(config)
		        .then(data => {
		          return data
		        })
		    })
```

**Comment by lagmanzaza** [comment]
`const bucket = gcs.bucket(fileBucket);

    const thumbFileName = `${fileName}_100X100`;
    const thumbFilePath = path.join(path.dirname(filePath), thumbFileName);

    // Create write stream for uploading thumbnail
    const thumbnailUploadStream = bucket.file(thumbFilePath)

    const pipeline = sharp();
    // Create Sharp pipeline for resizing the image and use pipe to read from bucket read stream
    pipeline
      .resize(profilePicHomePage[0], profilePicHomePage[1])
      .max()
      .pipe(thumbnailUploadStream.createWriteStream({
        metadata: {
          contentType: 'image/jpeg',
          metadata: {
            custom: customMetadata
          }
        }
      }));
    bucket.file(filePath).createReadStream().pipe(pipeline);`

This my code, So I don't know how to get file URL after pipe

**Comment by nicolasgarnier** [comment]
@lagmanzaza 
After compressing the iamge. You should be re-uploading it in Google Cloud Storage (using `bucket.upload`).

Once that's done you can generate a downloadURL (using `getSignedUrl `)

This is what the code shown by @joemanfoo does. You can refer to it.

One additional step would be to save the download URL somewhere so that you can retrieve it on the client (I'm guessing that's what you want to do...) for that you could save the download URL you generated in the Realtime  Database for instance.

If you are looking for an example we are doing this in the generate-thumbnail sample:

https://github.com/firebase/functions-samples/blob/master/generate-thumbnail/functions/index.js

**Comment by lagmanzaza** [comment]
Thank you very much

**Comment by rodrigoreal** [comment]
@lagmanzaza can you share how did you accomplish that?

**Comment by rodrigoreal** [comment]
Ok, got it working.
```
// Get the file name.
      const fileName = path.basename(filePath);
      // Exit if the image is already a thumbnail.
      if (fileName.startsWith('thumb_')) {
        console.log('Already a Thumbnail.');
        return;
      }
    
      // Download file from bucket.
      const bucket = gcs.bucket(BUCKET);
    
      // We add a 'thumb_' prefix to thumbnails file name. That's where we'll upload the thumbnail.
      const thumbFileName = `thumb_${fileName}`;
      const thumbFilePath = path.join(path.dirname(filePath), thumbFileName);
      const thumbFile = bucket.file(thumbFilePath);
      // Create write stream for uploading thumbnail
      const thumbnailUploadStream = bucket.file(thumbFilePath).createWriteStream({
        metadata: {
          contentType: 'image/jpeg'
        }
      });
    
      // Create Sharp pipeline for resizing the image and use pipe to read from bucket read stream
      const pipeline = sharp();
      pipeline
        .resize(THUMB_MAX_WIDTH, THUMB_MAX_HEIGHT)
        .max()
        .pipe(thumbnailUploadStream);
    
      bucket.file(filePath).createReadStream().pipe(pipeline);
    
      const streamAsPromise = new Promise((resolve, reject) =>
        thumbnailUploadStream.on('finish', resolve).on('error', reject));

      streamAsPromise.then(() => {
        console.log('Thumbnail created successfully');
        const config = {
          action: 'read',
          expires: '03-01-2500'
        };
        thumbFile.getSignedUrl(config).then((thumbResult) => {
          console.log('Got Signed URLs.');
          const thumbFileUrl = thumbResult[0];
          resolve({ thumbnail: thumbFileUrl });
        });
      });
```

**Comment by vercetti11** [comment]
Expires next day even though specifying the date 03-01-2500 

`const config = {
      action: "read",
      expires: "03-01-2500"
    };
    const results = await Promise.all([
      thumbFile.getSignedUrl(config),
      file.getSignedUrl(config)
    ]);`

**Comment by Ridermansb** [comment]
It's not clear on any documentation how to get URL  on admin to be used on `<img>` tags for instance.

The `expires` won't work because the maximum date is 7 days, several examples are wrong ...

You can see on documentation..

https://cloud.google.com/storage/docs/access-control/signed-urls#example

or here ...

https://googleapis.dev/nodejs/storage/latest/File.html#getSignedUrl

Examples like this one.. will expire in 7 days..... 

https://github.com/firebase/functions-samples/blob/5cf35c2d4a0965e4e70165add3127f50cfcaa3c2/generate-thumbnail/functions/index.js#L87
