### ISSUE TITLE
Error on deploy (I think)?

### ISSUE THREAD

**Issue by beratuslu** [firebase/functions-samples#261]
Hello, 

I am having following error, event.params is coming as an empty object and it gives error of: Unhandled rejection. And When I run the command of firebase deploy. It doesnt uptades the code I wrote. I understand coz of I am changing the logs I wrote but I cant see what I wrote in the logs. It remains early codes that I wrote. What is wrong?

![image](https://user-images.githubusercontent.com/94031/32005633-6f1cb794-b9ad-11e7-8737-1273601db2f8.png)

**Comment by inlined** [comment]
This looks like you hit both a bug and an error:

1. Your code seems to not be returning the Promises you create. This is always a bug because _even on success_ the Cloud Function will start to shut down while you still have work being done in the background.
2. Your code had another actual error that caused the Promise to fail. This can often be because an API call fails, but the bug in "Firebase.child failed" seems to suggest that there's a code issue.

The best I can tell from your logs suggests that you're trying to use string interpolation (aka [Template Literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals)) with ${deviceUid} but that requires you to use the backtick character (`) not the double quote character (") when defining your string.
