### ISSUE TITLE
google-sheet-sync outdated code Promise.success() is not a function

### ISSUE THREAD

**Issue by MasonP57** [firebase/functions-samples#272]
I'm working on getting the google-sheet-sync sample up and running, there have been a lot of difficulties. Currently I have managed to actually get updates to a sheets document but this is intermittent. (if I deploy my firebase code and then make the call to the function to run, it'll work. Kind of weird and might be a bug).

Right now I'm getting the error "Promise.success() is not a function." Some google-fu shows that this is because the function success() has been removed from Angular and then() should be used instead.

This would need to be updated in the sample. There's also another line that is hardcoded but outdated: line 65. Where `const FUNCTIONS_REDIRECT` is defined, it uses an outdated URL format.

And if someone could post how to fix the code, that would be very handy for me. I don't really know what I'm doing haha.

[Edit] I can consistently get everything to work if I run `firebase deploy` and then refresh the /testsheetwrite URL listed in the sample. After that it never works again and says `Promise.then() is not a function` or `Promise.success() is not a function`

**Comment by prescottprue** [comment]
Yeah it should be `Promise.resolve` instead I think. After I fixed that, I got things working.


It was honestly much easier for me to get the example running with a serviceAccount and JWT auth instead of using the redirect and getting a token (obviously changes things a bit since your privileges are based on that service account instead of a users personal google login).

**Comment by nicolasgarnier** [comment]
Should be fixed now :)

My fault when I removed the Bluebird Promise implementation that was used int this sample I forgot to adapt this call.
