### ISSUE TITLE
Node 8 now in lts so need of es7 sample

### ISSUE THREAD

**Issue by pantharshit00** [firebase/functions-samples#278]
### How to reproduce these conditions
Cant say but see https://nodejs.org Node 8 is now in LTS. As the docs say cloud functions use node lts so is there support for async await out. If so you should remove es7 example

**Comment by prescottprue** [comment]
@pantharshit00 Pretty sure that cloud functions are still running Node `6.11.*` runtimes, so it is still nice to have this example (since you want to develop with the same node version you are running when deployed). An example helps keep a clear pathway to using babel in the meantime.

All of that said, I am not sure of the schedule for changing the functions runtime.

**Comment by inlined** [comment]
@prescottprue is correct. There's a lot of work involved in adding a new runtime to Cloud Functions and we're not there yet. Node 6.11.x is still GCF's version of Node. If you really want `async` and `await`, I'd recommend checking out TypeScript. We have a sample project in this repo that shows a configured TypeScript project and proper support in the CLI for setting up new projects with TypeScript is coming soon.
