### ISSUE TITLE
Unable to deploy functions or delete them after failed deployment. Also unable to disable the Cloud Functions API.

### ISSUE THREAD

**Issue by rishsriv** [firebase/functions-samples#280]
My deployments of Google Cloud Functions have been failing with the error

```
status: {
   code:  13    
   message:  "Failed to initialize a region"    
  }
```

When trying to delete the functions with `gcloud beta functions delete function_name`, the following error occurs: `ERROR: (gcloud.beta.functions.delete) OperationError: code=13, message=Failed to initialize a region`.

I had first enabled the Cloud Function API when it was in its Alpha phase, and had read that disabling and then re-enabling the API can solve this problem. However, the following error occurred when trying to disable the API: `Enable/disable steps failed for services [cloudfunctions.googleapis.com]`.

Any workarounds? Help would be very much appreciated - thanks!

**Comment by inlined** [comment]
Hi @rishsriv, sorry to respond so late. I'm going to close this bug report since it's not an actual issue with any of the code samples. If you're still running into problems, can you [file a ticket](https://firebase.google.com/support/contact/troubleshooting/)? This will help us track the core product issue in the appropriate places and get you sorted out.
