### ISSUE TITLE
isomorphic-react-app with code-splitting Sample!

### ISSUE THREAD

**Issue by valorloff** [firebase/functions-samples#321]
Due the fact that the functions local/runtime environment is slightly different from the regular dev-server/VM, and therefore hard to configure SSR code-split, it would be highly desirable that working sample!
it would be interesting to many people.
Thanks!

**Comment by nicolasgarnier** [comment]
@valorloff 

I just fixed the isomorphic-react-app sample in https://github.com/firebase/functions-samples/commit/77c426bf71ebe92336bcf6377ea5d0b23195d7e3

The sample was broken since a change in the latest Firebase SDK did not allow using the server-side configuration in the Client SDK.

Now the sample always uses the Client SDK to load data the same way on the client or the server.

Let me know if you had other issues with this sample.

**Comment by valorloff** [comment]
Yes, i know about Client SDK and long time used it instead Admin SDK!
But I'm talking about code-split example!
