### ISSUE TITLE
Add testing, linting, and building

### ISSUE THREAD

**Issue by samtstern** [firebase/functions-samples#325]
@nicolasgarnier would you be open to adding something like this:
https://github.com/firebase/snippets-node/pull/11

It's a few parts:

  * Use `lerna` to build and test each module
  * Lint all source files against a single `eslint` config to ensure correctness and consistency

If so I'd be happy to implement / assist implementation.

**Comment by nicolasgarnier** [comment]
@samtstern Hey! Sure that would be nice :)

Some notes:
 - There is not a lot of tests unfortunately, the only tested sample is https://github.com/firebase/functions-samples/tree/master/quickstarts/uppercase/functions
 - There is [now](https://github.com/firebase/functions-samples/pull/306) have an ESlint config file inside each individual sample functions directory. This is in order for enforce checking styling on deploy (The plan is to add a `presubmit` rule to check styling on Functions deploy). We added a rule that forces having a `return` statement inside all Promises. We did this because one of the main mistakes developers do is forgetting to chain the Promises in their code and this should help.
