### ISSUE TITLE
fcm-notifications - data structure for storing fcmToken could be better?

### ISSUE THREAD

**Issue by choopage** [firebase/functions-samples#397]
### How to reproduce these conditions

**Sample name or URL where you found the bug**
fcm-notifications

**Failing Function code used (including require/import commands at the top)**
I think the data structure for storing the fcm token in the sample can better.

**Steps to set up and reproduce**
Line 72 seemed to indicate that the data structure for storing the fcm token is

**Sample data pasted or attached as JSON (not an image)**
```  
{
   users: {
      ${followedUid}: {
         notificationTokens: {
            ${fcmToken1}: true,
            ${fcmToken2}: true,
            ${fcmToken3}: true,
         }
      }
   }
}
```

Wouldn't the below data structure better for storing fcmToken also see [reference](https://stackoverflow.com/q/50171602/3073280) by @TheTiger?
```
{
   users: {
      ${followedUid}: {
         notificationTokens: {
            ${auto-generated-id}: { id: fcmToken1 },
            ${auto-generated-id}: { id: fcmToken2 },
            ${auto-generated-id}: { id: fcmToken3 },
         }
      }
   }
}
```

Would the [fcmToken contains](https://stackoverflow.com/questions/39959417/what-is-the-maximum-length-of-an-fcm-registration-id-token)[ illegal character ](https://stackoverflow.com/a/20363114/3073280) in the future that may be not permissible to be saved as Realtime database key?

**Comment by nicolasgarnier** [comment]
I chose to save the FCM tokens as keys because it is a bit more efficient because all you have to do is one `set` operation each time you fetch the token.

Browser sometimes change their FCM tokens and often return the same token as before if you get it again so if you can't simply just do a `.push`. With the second data structure mentioned you'll need to check and make sure the token is not saved twice (you'll need to add an index on the `id` value, check if it exists and then write).

This can work too but just requires a little bit more input/output to the Firebase DB.

But with the first data structure all you have to do is just one write every time your app loads or when the key gets refreshed. You can avoid potential issues with disallowed characters in keys by encoding the token in URL safe base64 (for instance) and decoding it on the client.
