### ISSUE TITLE
Firebase search by child Key 

### ISSUE THREAD

**Issue by JosePatricio** [firebase/functions-samples#425]
![firebasequesiton](https://user-images.githubusercontent.com/4383014/41917202-696996fa-791f-11e8-802d-90c809da82e0.png)

Im trying to get the whole node by Key.

I have this so far but no sucess ;(

```js
  firebase.database().ref('localities').orderByKey().equalTo('5phvF52891M3ABkFqJDnGr2HC8E2')
    .on("value", function (snapshot) {
      console.log('value ', snapshot.val());
      snapshot.forEach(function (data) {
        console.log('key ', data.key);
      });
    });
```

**Comment by nicolasgarnier** [comment]
I'm really not sure but you can try `orderByValue()` instead of `orderByKey()`.

If this fails you probably want to do re-organise your data. The top level categories like "Quito" or "Otavalo" should be an attribute of the element. like `region: "Provincia de Imbabura"` it would be more flexible for searching.

PS: Next time please use Stack Overflow to ask such question.
