### ISSUE TITLE
PubSub example missing return value

### ISSUE THREAD

**Issue by klevismino** [firebase/functions-samples#496]
Hello @nicolasgarnier 

I just noticed that the [PubSub example code](https://github.com/firebase/functions-samples/blob/Node-8/quickstarts/pubsub-helloworld/functions/index.js) has no return value. I think there should be a Promise returned, otherwise you get the following error on Stackdriver Logs: "Function returned undefined, expected Promise or value"

**Comment by kariem** [comment]
Same here: Adding `return 0;` at the end of the function does not show the error message. See also [discussion on Stackoverflow][1], specifically [this comment][2]:

> From what I was told by the firebase support it sounds like things are going to remain this way.

Would you like a PR with the corresponding `return` statements added at the end of each method? Otherwise the current code produces errors.

[1]: https://stackoverflow.com/a/47145880 "Answer to Google Firebase Error(Function returned undefined, expected Promise or value)"
[2]: https://stackoverflow.com/questions/47128440/47145880#comment81744487_47145880 "Comment by Aaron Jo"

**Comment by nicolasgarnier** [comment]
Thanks for the report! I've added some `return null;` in the sample
