### ISSUE TITLE
Unexpected token mailTransport

### ISSUE THREAD

**Issue by AndrewNB** [firebase/functions-samples#537]
I am attempting to send an email via nodemailer when a new firebase auth user is created.  I have attempted this in serveral ways including on write to db.  

I have followed the example here: https://github.com/firebase/functions-samples/blob/master/quickstarts/email-users/functions/index.js

I have configured gmail username and password, I have installed nodemailer and am running node v10.15.0.

When I try to deploy the cloud function I recieve the following error:
148:11  error  Parsing error: Unexpected token mailTransport

After getting that error using my own customised version, I attempted the function as is in the example:

```js
exports.sendEmailConfirmation = functions.database.ref('/users/{uid}').onWrite((change) => {

const snapshot = change.after;
  const val = snapshot.val();

  if (!snapshot.changed('subscribedToMailingList')) {
    return null;
  }

  const mailOptions = {
    from: '"Spammy Corp." <noreply@firebase.com>',
    to: val.email,
  };

  const subscribed = val.subscribedToMailingList;

  // Building Email message.
  mailOptions.subject = subscribed ? 'Thanks and Welcome!' : 'Sad to see you go :`(';
  mailOptions.text = subscribed ?
      'Thanks you for subscribing to our newsletter. You will receive our next weekly newsletter.' :
      'I hereby confirm that I will stop sending you the newsletter.';
  
  try {
    await mailTransport.sendMail(mailOptions);
    console.log(`New ${subscribed ? '' : 'un'}subscription confirmation email sent to:`, val.email);
  } catch(error) {
    console.error('There was an error while sending the email:', error);
  }
  return null;
});
```

Any ideas what I may be doing wrong?

**Comment by halfbug** [comment]
hi did you found solution, i am having the same one

**Comment by AndrewNB** [comment]
> hi did you found solution, i am having the same one

Not really.  I used sendgrid.  Heres a snippet that I used to get it working with sendgrid, you may be able to adapt it to nodemailer. 

```
exports.welcomeEmailOnSelfSignup = functions.database.ref(`/users/{userId}/emails/welcomeEmail`).onWrite((change, context)=> {
  const email = change.after.val();
  const welcomeGift  = context.params.welcomeGift;
  const userId  = context.params.userId;
   return admin.database()
  .ref(`/users/${userId}/emails/welcomeGift`)
  .once('value')
  .then(snapshot => snapshot.val())
  .then(email => { 
    const msg = {
        to: /*email.email*/,
        from:/*from email */,
        subject:  /*Subject*/,
        templateId: /* Template id (create this in sendgrid)*/,
        dynamicTemplateData: {
          name: email.username,
        }
    };
    return sgMail.send(msg)
  })
  .then(() => console.log('email sent!') )
  .catch(err => console.log(err) )
});
```

**Comment by jhuleatt** [comment]
I know this is very late, but this is failing because you didn't declare your original function as `async`.

[This](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgzgOjsAdgEwKIFsCGBLAGwGEIUAzPKXGPUgAgF46yBXFAYxtMTRxhwBGOZAijAyACgDkAehbIocGQG8WeNAF8pASgSkA6lDwxgEiewAWOFAHNg2xgD46ygFCv23GHTgocYOAsIbyZLazsEHDITKABuVzo6TxQ4bwA3HAJGHz8AoJgEDIIJbXiEujwyOgkAQl9_QOCEMNtgNGk4FgE4diMBNoAVCABZfAI8WwAZPFSdBzdExLEYFigUOhQWAgJ4xI13ROTUulxCAHkwLhTshcWyKAgsAC46KQAiAGUwHCwsAE86CQoGAEG86AAeFDQYBgAh_AACFDEQhEniwjikABpyokYBAXkUEMBTgRsXsyocvD4uj0-m1soTOt1enh-mghqNCBMbNNUhS6DIZHQAEJqAhobl0bBjE7AOBwHARcoki5XRBMgBWwE42SZtNZ9IA_K8BlYUABrOB0axoOj6YAENHAGpSOgvKQfHC2vE-YDAOh_CAsOg2CBugAG0l2JzGqtoKQQJhAIWpzLptsNOMWUlN1ktAaDzGgqf1AklPqDUA2wAA7nACMAYDEEHQAJqFmuELJidjAPBpf2V6vJug1v3muHVusNpvAKAIV1PLOJKQASToFjnwAEAOSSKwdBgVm86872x8eLAvvQksDwaP_pQtfrjebUmj5RgUABt0SOBr-DeCSAxQNYcCQLASCoGgnLFCqlzxnApRZkcEANggBAQDYEjhgAcrWdAACTKHqLJsnQxpSIurxsFIGikUYCH0HulDUPGdDEjKyAoN4eJPOGmJ0ISnGEMhexJHwlgSHODxQPMKHcGhwBElAsnSKaW6jsI1rrDJxY1hYhD-txEq2Iem4cSSTxYhxqnQGJdD7EsjarOsmzbPEGilEAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Ces2017%2Creact%2Cstage-2&prettier=false&targets=&version=7.5.5&externalPlugins=) is your original function, and [this](https://babeljs.io/en/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=KYDwDg9gTgLgzgOjsAdgEwKIFsCGBLAGwGEIUAzPKXGPUgAgF46yBXFAYxtMTRxhwBGOZAijAyACgDkAehbIocGQG8WeNAF8pASgSkA6lDwxgE4QE8OdCewAWOFAHNg2xgD46ygFBf23GHRwKDhgcLYQAUx2Ds4IOGQmUADcXnR0fihwAQBuOASMgcGh4TAIuQQS2impdHhk1gCEQSFhEQjRTsBo0nAsAnDsRgJdACoQALL4BHhOADJ4WTqu3mlpYjAsUCh0KCwEBClpGj5pGVl0uIQA8mBcmQUrq2RQEFgAXHRSAEQAymA4WCw5joJCgYAQXzoAB4UNBgGACOYAAIUMRCER-LBuKQAGhqaRgEA-5QQwEuBDxR2qp38gT6AyGXQKJN6_UGeGGaDGk0IM0c8yy1LoMhkdAAQmoCGg-XRsFMLsA4HAcLEauSbndEKyAFbATgFVkMjlMgD8nxG9hQAGs4HQHGg6PpgARMcAGlI6B8pD8cA7CYFgMA6OYICw6I4IJ6AAbSQ4XKYa2iZBAmECROlsxkOk341ZSC0OG3B0PMaAZo0CGX-0NQHbAADucAIwBgiQQdAAmiX64R8mJ2MA8NkgzW62m6PXA1bEXXG83W8AoAgPW9c2kpABJOi2RfAATAjKorB0GD2AJbnv7QKEsAB9AykNh09BlANpstttSOM1GBQYGPNIcHrfAAnJEYoAcOBIFgJBUDQHkKnVW4kzgKpczOCBmwQAgIEcCQowAOQbOgABJlENdlOToM0pBXT42CkDQKKMZD6EPShqCTOgyXlZAUACQk3ijHE6BJHjCDQo50j4OwJEXF4oGWdDuEw4BSSgBTpAtXcJ2EO1tnkst61sQggz46UnBPHduPJN5cW4jToEkuhjjWFtNm2XZ9hSDQqiAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=true&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=es2015%2Ces2017%2Creact%2Cstage-2&prettier=false&targets=&version=7.5.5&externalPlugins=) is the fixed function.
