### ISSUE TITLE
Make Search Feature with firebase realtime database with kotlin

### ISSUE THREAD

**Issue by 4RSIM3R** [firebase/functions-samples#540]
Can someone help me to make a search feature with kotlin 
Are there specific keywords to do queries like this? like a "LIKE" in sql...

**Comment by jhuleatt** [comment]
Cloud Functions for Firebase only supports JavaScript

**Comment by puf** [comment]
Firebase doesn't support full-text search operators such as SQL's `LIKE` in its queries. If you need such queries, consider using an additional service (such as Algolia). See these related questions on Stack Overflow:

* https://stackoverflow.com/questions/10559191/firebase-and-indexing-search
* https://stackoverflow.com/questions/22506531/how-to-perform-sql-like-operation-on-firebase
* https://stackoverflow.com/questions/42720482/can-i-use-firebase-cloud-functions-for-search-engine
* https://stackoverflow.com/questions/33867185/searching-in-firebase-without-server-side-code
* https://stackoverflow.com/questions/46261573/how-to-search-anywhere-in-string-in-firebase-database-android

I'd recommend posting this type of question on Stack Overflow in the future, since it's not related to a specific sample in this repo, but a more general "how to" question about using Firebase. Such questions are a better fit for Stack Overflow, and you probably would have gotten a response there sooner.

**Comment by 4RSIM3R** [comment]
Ok Thank You very much...
