### ISSUE TITLE
Please Update also Function in Typescripts 

### ISSUE THREAD

**Issue by iMnoorfahad** [firebase/functions-samples#626]
Please update all function also in typescript?
======================================
i got some problem to use this function bkz my all function in typescript so please update in typescript also  this is best for every typescript user

**Comment by jhuleatt** [comment]
While it would help Typescript developers, it would make it difficult for JS developers to use this repo. Since Typescript is a superset of JS, we'll continue maintaining most of the functions in this repo as JS, with some [Typescript examples](https://github.com/firebase/functions-samples/tree/master/typescript-getting-started).
