### ISSUE TITLE
gRPC binary module version mismatch

### ISSUE THREAD

**Issue by olihop** [firebase/functions-samples#628]
I don't exactly know how to document this so apologies if it's hard to read. Following the steps in the guide for the stripe sample, on running 'firebase deploy', gives me this:

```
Error: Error parsing triggers: Failed to load gRPC binary module because it was not installed for the current system
Expected directory: node-v64-darwin-x64-unknown
Found: [node-v72-darwin-x64-unknown]
This problem can often be fixed by running "npm rebuild" on the current system
Original error: Cannot find module '/**[omitted]**/functions-samples/stripe/functions/node_modules/grpc/src/node/extension_binary/node-v64-darwin-x64-unknown/grpc_node.node'
1) If you want to compile the package/file into executable, please pay attention to compilation warnings and specify a literal in 'require' call. 2) If you don't want to compile the package/file into executable and want to 'require' it from filesystem (likely plugin), specify an absolute path in 'require' call using process.cwd() or process.execPath.
```

Strangely, node -v returns 12.12.0 which should have a NODE_MODULE_VERSION of 72.

npm install and npm rebuild in the functions directory don't have any effect. Reinstalling node doesn't do anything either.

This is on macOS 10.14.2.

**Comment by francisrod01** [comment]
Hi @olihop, please provide more details!
I happened to me once because I'm using `nvm` as node version manager, and I was using a different version of node to front and backend.

> Let's suppose that you use something like that to manage your node version.

Try the following instructions:

1. remove your `node_modules` folder in both projects `app` and `functions`
2. type `npm clean` for both cases
3. type `npm cache clean`
4. then `npm i` for both cases

That's it!
See it working properly. ;)

**Comment by jhuleatt** [comment]
+1 to @francisrod01's comment. gRPC is very sensitive to npm version, so clearing the `node_modules` folder and `package-lock.json` is the best place to start.
