### ISSUE TITLE
firebase payment sites output google network

### ISSUE THREAD

**Issue by Escanor2019** [firebase/functions-samples#661]
Is it possible to process payments from non-Paypal and Stripe sites?

paysafecard, bitcoin-sites-api, regional-country-payment-site?

I read that firebase does not accept external network (non-Google), why only Stripe and Paypal?

**Comment by samtstern** [comment]
@Escanor2019 these are just examples.  It's possible to process payments using any provider in Functions, we just chose to show Stripe and Paypal because those are most common.

For general questions try asking on StackOverflow or another forum.  We don't plan to add more payment examples to this repo.
