### ISSUE TITLE
functions: missing required API cloudbuild.googleapis.com. Enabling now...

### ISSUE THREAD

**Issue by Daniel-Vnzla** [firebase/functions-samples#764]
I get this error:

+  functions: Finished running predeploy script.
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudfunctions.googleapis.com is enabled
!  functions: missing required API cloudbuild.googleapis.com. Enabling now...

Error: HTTP Error: 400, Billing account for project '385437835946' is not found. Billing must be enabled for activation of service(s) 'cloudbuild.googleapis.com,containerregistry.googleapis.com' to proceed.

**Comment by jhuleatt** [comment]
@Daniel-Vnzla Cloud Functions requires a billing account for Node 10 functions: https://firebase.google.com/support/faq#expandable-10

Do you have the Blaze plan enabled on your project?

**Comment by TimMensch** [comment]
The Spark plan allegedly supports Cloud Functions "on Node 8 only", but it _also_ won't let us select Node 8 (because it's deprecated).

What's up with that? Shouldn't the Spark plan support the minimum allowed Node runtime?

**Comment by samtstern** [comment]
@TimMensch see the FAQ here:
https://firebase.google.com/support/faq?authuser=0#functions-runtime

Once Node.js 8 was deprecated we decided to stop developers who were not already using it from using it because those functions will **stop executing** in just a few months.  If you want to experiment with Functions without a credit card it's best to use the emulator.

**Comment by TimMensch** [comment]
@samtstern I guess the nature of my question is _why isn't Node 10 allowed on Spark plans_?

And if you've decided not to allow Node 10 on Spark plans, and Node 8 is permanently disabled, then why does the pricing page still claim Spark plans support Cloud Functions _at all_?

At the moment the pricing page is misrepresenting reality for anyone who's signing up right now.

**Comment by samtstern** [comment]
I agree with you about the pricing page I'll see if I can get that updated earlier. It's technically true (if you downgraded to and old CLI and used Node 8 it would let you deploy) but not meaningfully true.

Starting with Node 10 all Google Cloud Functions deploys go through Cloud Build and the images are stored in a multi-regional Cloud Storage bucket.  Neither of those products is compatible with the Spark plan, so therefore neither is Cloud Functions. This is a good infrastructural decision that is bad for people trying to evaluate Firebase on the Spark plan, we wish we had a better option but we did not. 

We still offer a free tier for Cloud Functions on the Blaze plan and I can tell you that in all of my personal projects I see a monthly charge of < $0.10 (mostly $0.01) for my Cloud Functions experiments. Annoying for sure but not breaking the bank.

**Comment by TimMensch** [comment]
This is for a client project, and I'd told the client we'd be good on the Spark plan based on the Pricing page. :( 

Given the story floating around about the team that accidentally ended up with a half million dollar Google Cloud Function bill because of poor recursive crawling of pages, it makes some people a bit gun shy about possible exploding costs. Would _really_ like to see _caps_ on such charges, where Google would cut off the service rather than charge more than $1000 in a month, for instance.

I know the "budget" warning exists, but it checks _daily_. They hit a half million in GCP fees in _hours_, if I'm not mistaken. It also just sends emails, which I might not get for a half day or more; I'd really, really like to see a hard cap on costs to prevent accidental bankruptcy, even if I _am_ confident that I wouldn't make a similar mistake. AWS has this same limitation, I know, but it would be really nice for small businesses to have a guaranteed liability limit on their sites; it's something that pushes some developers I know away from the big hosts to hosts like Linode that do offer a guaranteed cap on monthly costs.

That's why Spark was attractive; not because I was worried about the likely cost of a working app, but the worst-case disaster of a runaway loop that could run up a huge bill before I even noticed. If there were a "Spark+" that cost $5/month but had caps instead of potential runaway costs? I'd probably recommend that to the client, even though under Blaze it might be $1/month or less for all of the services.

**Comment by samtstern** [comment]
@TimMensch I don't know what else to say except that you're absolutely right.  We've made negative progress in our pricing in the last year or so. We had to get rid of the Flame plan ($25 cap plan, which is what you call Spark+) and we had to move Functions out of the creditcard-less free tier.

We're pushing really hard to bring back billing caps for developers in a way that's internally sustainable. We want developers to sleep well at night. Unexpected bills are really bad for us too!  They generate bad PR (I've read all of those posts) and 9/10 times we end up refunding them which is expensive for us.

We truly appreciate that people like you take the time to share your thoughts on the matter. I hope you can hang with us until we fix it!

**Comment by samtstern** [comment]
@Daniel-Vnzla sorry that @TimMensch and I hijacked your issue!  I'm going to close this as we're pretty far from your original technical issue and @jhuleatt has suggested the correct solution.

@TimMensch if you have more to say on this topic you can always email me, my email address is in my GitHub profile.

**Comment by samtstern** [comment]
@TimMensch just FYI due to your feedback we went and updated the pricing page to be much more clear about the fact that Cloud Functions require Blaze:

<img width="1129" alt="Screen Shot 2021-01-22 at 10 40 00 AM" src="https://user-images.githubusercontent.com/8466666/105480900-5790c800-5c74-11eb-894d-0f9229a34b58.png">

**Comment by TimMensch** [comment]
I noticed! Thanks for getting that updated!

**Comment by InfinityCoder88** [comment]
Hi guys, I have **Blaze** plan and I still get these errors:
`ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
+  functions: required API cloudbuild.googleapis.com is enabled
+  functions: required API cloudfunctions.googleapis.com is enabled
i  functions: preparing functions directory for uploading...`

On my second project on Firebase, any ideas why thanks in advance!

**Comment by dijour** [comment]
^ @samtstern Bump on @InfinityCoder88 's issue. I have the same problem. Blaze plan and getting a mysterious deploy bug. 
![image](https://user-images.githubusercontent.com/26984516/127809781-7ca1d2d7-69e3-4c64-af11-2cb51725420a.png)

**Comment by jhuleatt** [comment]
@dijour it sounds like it may be a project-specific issue. Please [contact Firebase support](https://firebase.google.com/support/troubleshooter/functions/deploy) with the contents of `firebase-debug.log`.

**Comment by stxwright** [comment]
The information on the "Upgrade > Firebase billing plans" dialog also seems to be out of date, given that Functions are no longer available on the Spark plan. It currently says "Usage quotas for Database, Firestore, Storage, **Functions**, Phone Auth, Hosting and Test Lab".
