### ISSUE TITLE
If the firefox is closed, sending a push notification using curl always returns an "InternalServerError"

### ISSUE THREAD

**Issue by imiotis** [firebase/functions-samples#791]
I am using FCM legacy HTTP API.
I am sending requests to https://fcm.googleapis.com/fcm/send by using curl. In this example, I used Postman. In my project I am sending using PHP, which gives me the same result.
![git](https://user-images.githubusercontent.com/32706965/100356214-fba71b80-3003-11eb-91b8-649a61b5e572.png)

**Comment by jhuleatt** [comment]
Closing this out because it doesn't follow the issue template. @imiotis if you're still having trouble with this (and it is related to code in this repository), please re-file with the information requested in the issue template. If you're not using code in this repository, please contact [Firebase support](https://firebase.google.com/support) instead
