### ISSUE TITLE
full-text search, AlgoliaSearchNetworkError

### ISSUE THREAD

**Issue by tsebvaan** [firebase/functions-samples#89]
Hi, I followed the readme on full-text search for cloud functions. Adding,modifying or deleting the blog-posts will trigger an error. Same for adding,modifying and deleteing for search/query/{queryid}. 

I created an account on algolia then get the ApplicationID, and Admin API Key.
firebase functions:config:set algolia.key="<ApplicationID"> algolia.secret="<Admin API Key">

![123](https://cloud.githubusercontent.com/assets/23137338/24332931/c7ce9e1c-1281-11e7-94a3-809b4174ca4e.jpg)

**Comment by prescottprue** [comment]
You need to upgrade to the Blaze plan (paid).

**Comment by tsebvaan** [comment]
Oh , so it is not for free :( I'm still a student though. May I ask if I can do elasticsearch without paying or having crefit card?  By the way thanks.

**Comment by nicolasgarnier** [comment]
Yes the issue is hapening because you need to enable billing on your account. For abuse protection reasons we had to disable external request for billingless accounts for now. After enabling billing there is still a large free tier so you likely won't get billed right away for Functions usage although the Realtime Database does not have a free tier so you'll get billed on that.

And yes you'll need a credit card to enable billing :/
